package de.blackforestsolutions.datamodel;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.ZonedDateTime;
import java.util.List;


@Getter
public final class ApiTokenAndUrlInformation {

    private final String apiName;
    private final String protocol;
    private final String host;
    private final Integer port;
    private final String apiVersion;
    private final String pathVariable;
    private final String departure;
    private final String arrival;
    private final ZonedDateTime departureDate;
    private final ZonedDateTime arrivalDate;
    private final String xOriginationIpKey;
    private final String xOriginationIp;
    private final String authorizationKey;
    /**
     * We need to update our bearer token for lufthansa request
     */
    @Setter
    private String authorization;
    private final String path;
    private final String hazelcastPath;
    private final String hazelcastWritePath;
    private final String hazelcastReadAllPath;
    private final String hazelcastSearchPath;
    private final String germanRailJourneyDeatilsPath;
    private final String germanRailDepartureBoardPath;
    private final String germanRailArrivalBoardPath;
    private final String germanRailLocationPath;
    private final ZonedDateTime germanRailDatePathVariable;
    private final String stationId;
    private final String journeyDetailsId;
    private final String locoApiFlightPath;
    private final String locoApiLocaterPath;
    private final String locoApiNearestAirportsPath;
    private final String locoApiNationalTrainPath;
    private final String locoApiRegionalTrainPath;
    private final String locoApiRideSharesPath;
    private final String locoApiRidesPath;
    private final String locoApiFootPath;
    private final String locoApiDirectConnectionPath;

    private final String datePathVariable;
    private final String searchChRoutePathVariable;
    private final String searchChResults;
    private final String searchChDelayParameter;
    private final String timePathVariable;
    private final String startLocation;
    private final String destinationLocation;
    private final String locationPath;
    private final String coordinatesPath;
    private final String searchChTermParameter;
    private final String searchChStationId;
    private final String searchChStationCoordinateParameter;
    private final String locationSearchTerm;
    private final String language;
    private final String authentificationUser;
    private final String authentificationType;
    private final String authentificationPassword;
    private final String stationListPathVariable;
    private final String journeyPathVariable;
    private final String travelPointPathVariable;
    private final Integer resultLength;
    private final Integer distanceFromTravelPoint;
    private final Integer resultLengthBeforeDepartureTime;
    private final Integer resultLengthAfterDepartureTime;
    private final String tariff;
    private final Boolean timeIsDeparture;
    private final Boolean hvvFilterEquivalent;
    private final Boolean hvvAllowTypeSwitch;
    private final Boolean allowTariffDetails;
    private final Boolean allowReducedPrice;
    private final Boolean allowIntermediateStops;
    private final Boolean hvvReturnContSearchData;

    private final String mic;
    private final String checksum;
    private final String mac;
    private final String hafasRtMode;
    private final String clientId;
    private final String clientSecret;
    private final String clientVersion;
    private final String clientName;
    private final String clientType;
    private final Integer transfers;
    private final Integer minTransferTime;
    private final String hafasProductionValue;
    private final String forDisabledPersons;
    private final String walkingSpeed;
    private final Boolean allowCoordinates;

    private final Coordinates departureCoordinates;
    private final Coordinates arrivalCoordinates;
    private final String outputFormat;

    private final Integer radius;
    private final Integer numberOfPersons;
    private final String currency;
    private final String sortDirection;

    private final List<Integer> ages;

    private ApiTokenAndUrlInformation(ApiTokenAndUrlInformationBuilder apiTokenAndUrlInformation) {
        this.protocol = apiTokenAndUrlInformation.getProtocol();
        this.host = apiTokenAndUrlInformation.getHost();
        this.port = apiTokenAndUrlInformation.getPort();
        this.apiVersion = apiTokenAndUrlInformation.getApiVersion();
        this.pathVariable = apiTokenAndUrlInformation.getPathVariable();
        this.departure = apiTokenAndUrlInformation.getDeparture();
        this.arrival = apiTokenAndUrlInformation.getArrival();
        this.departureDate = apiTokenAndUrlInformation.getDepartureDate();
        this.arrivalDate = apiTokenAndUrlInformation.getArrivalDate();
        this.xOriginationIpKey = apiTokenAndUrlInformation.getXOriginationIpKey();
        this.xOriginationIp = apiTokenAndUrlInformation.getXOriginationIp();
        this.authorizationKey = apiTokenAndUrlInformation.getAuthorizationKey();
        this.authorization = apiTokenAndUrlInformation.getAuthorization();
        this.path = apiTokenAndUrlInformation.getPath();
        this.hazelcastPath = apiTokenAndUrlInformation.getHazelcastPath();
        this.hazelcastWritePath = apiTokenAndUrlInformation.getHazelcastWritePath();
        this.hazelcastReadAllPath = apiTokenAndUrlInformation.getHazelcastReadAllPath();
        this.hazelcastSearchPath = apiTokenAndUrlInformation.getHazelcastSearchPath();
        this.germanRailJourneyDeatilsPath = apiTokenAndUrlInformation.getGermanRailJourneyDeatilsPath();
        this.germanRailDepartureBoardPath = apiTokenAndUrlInformation.getGermanRailDepartureBoardPath();
        this.germanRailArrivalBoardPath = apiTokenAndUrlInformation.getGermanRailArrivalBoardPath();
        this.germanRailLocationPath = apiTokenAndUrlInformation.getGermanRailLocationPath();
        this.stationId = apiTokenAndUrlInformation.getStationId();
        this.journeyDetailsId = apiTokenAndUrlInformation.getJourneyDetailsId();
        this.germanRailDatePathVariable = apiTokenAndUrlInformation.getGermanRailDatePathVariable();
        this.datePathVariable = apiTokenAndUrlInformation.getDatePathVariable();
        this.searchChRoutePathVariable = apiTokenAndUrlInformation.getSearchChRoutePathVariable();
        this.searchChResults = apiTokenAndUrlInformation.getSearchChResults();
        this.searchChDelayParameter = apiTokenAndUrlInformation.getSearchChDelayParameter();
        this.locationSearchTerm = apiTokenAndUrlInformation.getLocationSearchTerm();
        this.timePathVariable = apiTokenAndUrlInformation.getTimePathVariable();
        this.startLocation = apiTokenAndUrlInformation.getStartLocation();
        this.destinationLocation = apiTokenAndUrlInformation.getDestinationLocation();
        this.locationPath = apiTokenAndUrlInformation.getLocationPath();
        this.coordinatesPath = apiTokenAndUrlInformation.getCoordinatesPath();
        this.searchChTermParameter = apiTokenAndUrlInformation.getSearchChTermParameter();
        this.searchChStationId = apiTokenAndUrlInformation.getSearchChStationId();
        this.searchChStationCoordinateParameter = apiTokenAndUrlInformation.getSearchChStationCoordinateParameter();
        this.language = apiTokenAndUrlInformation.getLanguage();
        this.authentificationUser = apiTokenAndUrlInformation.getAuthentificationUser();
        this.authentificationType = apiTokenAndUrlInformation.getAuthentificationType();
        this.authentificationPassword = apiTokenAndUrlInformation.getAuthentificationPassword();
        this.stationListPathVariable = apiTokenAndUrlInformation.getStationListPathVariable();
        this.journeyPathVariable = apiTokenAndUrlInformation.getJourneyPathVariable();
        this.travelPointPathVariable = apiTokenAndUrlInformation.getTravelPointPathVariable();
        this.resultLength = apiTokenAndUrlInformation.getResultLength();
        this.distanceFromTravelPoint = apiTokenAndUrlInformation.getDistanceFromTravelPoint();
        this.resultLengthBeforeDepartureTime = apiTokenAndUrlInformation.getResultLengthBeforeDepartureTime();
        this.resultLengthAfterDepartureTime = apiTokenAndUrlInformation.getResultLengthAfterDepartureTime();
        this.tariff = apiTokenAndUrlInformation.getTariff();
        this.timeIsDeparture = apiTokenAndUrlInformation.getTimeIsDeparture();
        this.hvvFilterEquivalent = apiTokenAndUrlInformation.getHvvFilterEquivalent();
        this.hvvAllowTypeSwitch = apiTokenAndUrlInformation.getHvvAllowTypeSwitch();
        this.allowTariffDetails = apiTokenAndUrlInformation.getAllowTariffDetails();
        this.allowReducedPrice = apiTokenAndUrlInformation.getAllowReducedPrice();
        this.allowIntermediateStops = apiTokenAndUrlInformation.getAllowIntermediateStops();
        this.hvvReturnContSearchData = apiTokenAndUrlInformation.getHvvReturnContSearchData();
        this.apiName = apiTokenAndUrlInformation.getApiName();
        this.checksum = apiTokenAndUrlInformation.getChecksum();
        this.mic = apiTokenAndUrlInformation.getMic();
        this.mac = apiTokenAndUrlInformation.getMac();
        this.hafasRtMode = apiTokenAndUrlInformation.getHafasRtMode();
        this.clientId = apiTokenAndUrlInformation.getClientId();
        this.clientSecret = apiTokenAndUrlInformation.getClientSecret();
        this.clientVersion = apiTokenAndUrlInformation.getClientVersion();
        this.clientName = apiTokenAndUrlInformation.getClientName();
        this.clientType = apiTokenAndUrlInformation.getClientType();
        this.transfers = apiTokenAndUrlInformation.getTransfers();
        this.minTransferTime = apiTokenAndUrlInformation.getMinTransferTime();
        this.hafasProductionValue = apiTokenAndUrlInformation.getHafasProductionValue();
        this.forDisabledPersons = apiTokenAndUrlInformation.getForDisabledPersons();
        this.walkingSpeed = apiTokenAndUrlInformation.getWalkingSpeed();
        this.allowCoordinates = apiTokenAndUrlInformation.getAllowCoordinates();
        this.arrivalCoordinates = apiTokenAndUrlInformation.getArrivalCoordinates();
        this.departureCoordinates = apiTokenAndUrlInformation.getDepartureCoordinates();
        this.outputFormat = apiTokenAndUrlInformation.getOutputFormat();
        this.radius = apiTokenAndUrlInformation.getRadius();
        this.numberOfPersons = apiTokenAndUrlInformation.getNumberOfPersons();
        this.currency = apiTokenAndUrlInformation.getCurrency();
        this.sortDirection = apiTokenAndUrlInformation.getSortDirection();
        this.locoApiFlightPath = apiTokenAndUrlInformation.getLocoApiFlightPath();
        this.locoApiLocaterPath = apiTokenAndUrlInformation.getLocoApiLocaterPath();
        this.locoApiNearestAirportsPath = apiTokenAndUrlInformation.getLocoApiNearestAirportsPath();
        this.locoApiNationalTrainPath = apiTokenAndUrlInformation.getLocoApiNationalTrainPath();
        this.locoApiRegionalTrainPath = apiTokenAndUrlInformation.getLocoApiRegionalTrainPath();
        this.locoApiRideSharesPath = apiTokenAndUrlInformation.getLocoApiRideSharesPath();
        this.locoApiRidesPath = apiTokenAndUrlInformation.getLocoApiRidesPath();
        this.locoApiFootPath = apiTokenAndUrlInformation.getLocoApiFootPath();
        this.locoApiDirectConnectionPath = apiTokenAndUrlInformation.getLocoApiDirectConnectionPath();
        this.ages = apiTokenAndUrlInformation.getAges();
    }

    @Getter
    @Setter
    @NoArgsConstructor
    public static class ApiTokenAndUrlInformationBuilder {
        private String apiName;
        private String protocol;
        private String host;
        private Integer port = -1;
        private String apiVersion;
        private String pathVariable;
        private String departure;
        private String arrival;
        private ZonedDateTime departureDate;
        private ZonedDateTime arrivalDate;
        private String xOriginationIpKey;
        private String xOriginationIp;
        private String authorizationKey;
        private String authorization;
        private String path;
        private String hazelcastPath;
        private String hazelcastWritePath;
        private String hazelcastReadAllPath;
        private String hazelcastSearchPath;
        private String germanRailJourneyDeatilsPath;
        private String germanRailDepartureBoardPath;
        private String germanRailArrivalBoardPath;
        private String germanRailLocationPath;
        private ZonedDateTime germanRailDatePathVariable;
        private String stationId;
        private String journeyDetailsId;
        private String datePathVariable;
        private String searchChRoutePathVariable;
        private String searchChResults;
        private String searchChDelayParameter;
        private String timePathVariable;
        private String startLocation;
        private String destinationLocation;
        private String locationPath;
        private String coordinatesPath;
        private String searchChTermParameter;
        private String searchChStationId;
        private String searchChStationCoordinateParameter;
        private String locationSearchTerm;
        private String language;
        private String authentificationUser;
        private String authentificationType;
        private String authentificationPassword;
        private String stationListPathVariable;
        private String journeyPathVariable;
        private String travelPointPathVariable;
        private Integer resultLength;
        private Integer distanceFromTravelPoint;
        private Integer resultLengthBeforeDepartureTime;
        private Integer resultLengthAfterDepartureTime;
        private String tariff;
        private Boolean timeIsDeparture;
        private Boolean hvvFilterEquivalent;
        private Boolean hvvAllowTypeSwitch;
        private Boolean allowTariffDetails;
        private Boolean allowReducedPrice;
        private Boolean allowIntermediateStops;
        private Boolean hvvReturnContSearchData;
        private String checksum;
        private String mic;
        private String mac;
        private String hafasRtMode;
        private String clientId;
        private String clientSecret;
        private String clientVersion;
        private String clientName;
        private String clientType;
        private Integer transfers;
        private Integer minTransferTime;
        private String hafasProductionValue;
        private String forDisabledPersons;
        private String walkingSpeed;
        private Boolean allowCoordinates;
        private Coordinates arrivalCoordinates;
        private Coordinates departureCoordinates;
        private String outputFormat;
        private Integer radius;
        private Integer numberOfPersons;
        private String currency;
        private String sortDirection;
        private String locoApiFlightPath;
        private String locoApiLocaterPath;
        private String locoApiNearestAirportsPath;
        private String locoApiNationalTrainPath;
        private String locoApiRegionalTrainPath;
        private String locoApiRideSharesPath;
        private String locoApiRidesPath;
        private String locoApiFootPath;
        private String locoApiDirectConnectionPath;
        private List<Integer> ages;

        public ApiTokenAndUrlInformationBuilder(ApiTokenAndUrlInformation apiTokenAndUrlInformation) {
            this.protocol = apiTokenAndUrlInformation.getProtocol();
            this.host = apiTokenAndUrlInformation.getHost();
            this.port = apiTokenAndUrlInformation.getPort();
            this.apiVersion = apiTokenAndUrlInformation.getApiVersion();
            this.pathVariable = apiTokenAndUrlInformation.getPathVariable();
            this.departure = apiTokenAndUrlInformation.getDeparture();
            this.arrival = apiTokenAndUrlInformation.getArrival();
            this.departureDate = apiTokenAndUrlInformation.getDepartureDate();
            this.arrivalDate = apiTokenAndUrlInformation.getArrivalDate();
            this.xOriginationIpKey = apiTokenAndUrlInformation.getXOriginationIpKey();
            this.xOriginationIp = apiTokenAndUrlInformation.getXOriginationIp();
            this.authorizationKey = apiTokenAndUrlInformation.getAuthorizationKey();
            this.authorization = apiTokenAndUrlInformation.getAuthorization();
            this.path = apiTokenAndUrlInformation.getPath();
            this.hazelcastPath = apiTokenAndUrlInformation.getHazelcastPath();
            this.hazelcastWritePath = apiTokenAndUrlInformation.getHazelcastWritePath();
            this.hazelcastReadAllPath = apiTokenAndUrlInformation.getHazelcastReadAllPath();
            this.hazelcastSearchPath = apiTokenAndUrlInformation.getHazelcastSearchPath();
            this.germanRailJourneyDeatilsPath = apiTokenAndUrlInformation.getGermanRailJourneyDeatilsPath();
            this.germanRailDepartureBoardPath = apiTokenAndUrlInformation.getGermanRailDepartureBoardPath();
            this.germanRailArrivalBoardPath = apiTokenAndUrlInformation.getGermanRailArrivalBoardPath();
            this.germanRailLocationPath = apiTokenAndUrlInformation.getGermanRailLocationPath();
            this.germanRailDatePathVariable = apiTokenAndUrlInformation.getGermanRailDatePathVariable();
            this.stationId = apiTokenAndUrlInformation.getStationId();
            this.journeyDetailsId = apiTokenAndUrlInformation.getJourneyDetailsId();
            this.datePathVariable = apiTokenAndUrlInformation.getDatePathVariable();
            this.searchChRoutePathVariable = apiTokenAndUrlInformation.getSearchChRoutePathVariable();
            this.searchChResults = apiTokenAndUrlInformation.getSearchChResults();
            this.searchChDelayParameter = apiTokenAndUrlInformation.getSearchChDelayParameter();
            this.timePathVariable = apiTokenAndUrlInformation.getTimePathVariable();
            this.startLocation = apiTokenAndUrlInformation.getStartLocation();
            this.destinationLocation = apiTokenAndUrlInformation.getDestinationLocation();
            this.locationPath = apiTokenAndUrlInformation.getLocationPath();
            this.coordinatesPath = apiTokenAndUrlInformation.getCoordinatesPath();
            this.searchChTermParameter = apiTokenAndUrlInformation.getSearchChTermParameter();
            this.searchChStationId = apiTokenAndUrlInformation.getSearchChStationId();
            this.searchChStationCoordinateParameter = apiTokenAndUrlInformation.getSearchChStationCoordinateParameter();
            this.locationSearchTerm = apiTokenAndUrlInformation.getLocationSearchTerm();
            this.language = apiTokenAndUrlInformation.getLanguage();
            this.authentificationUser = apiTokenAndUrlInformation.getAuthentificationUser();
            this.authentificationType = apiTokenAndUrlInformation.getAuthentificationType();
            this.authentificationPassword = apiTokenAndUrlInformation.getAuthentificationPassword();
            this.stationListPathVariable = apiTokenAndUrlInformation.getStationListPathVariable();
            this.journeyPathVariable = apiTokenAndUrlInformation.getJourneyPathVariable();
            this.travelPointPathVariable = apiTokenAndUrlInformation.getTravelPointPathVariable();
            this.resultLength = apiTokenAndUrlInformation.getResultLength();
            this.distanceFromTravelPoint = apiTokenAndUrlInformation.getDistanceFromTravelPoint();
            this.resultLengthBeforeDepartureTime = apiTokenAndUrlInformation.getResultLengthBeforeDepartureTime();
            this.resultLengthAfterDepartureTime = apiTokenAndUrlInformation.getResultLengthAfterDepartureTime();
            this.tariff = apiTokenAndUrlInformation.getTariff();
            this.timeIsDeparture = apiTokenAndUrlInformation.getTimeIsDeparture();
            this.hvvFilterEquivalent = apiTokenAndUrlInformation.getHvvFilterEquivalent();
            this.hvvAllowTypeSwitch = apiTokenAndUrlInformation.getHvvAllowTypeSwitch();
            this.allowTariffDetails = apiTokenAndUrlInformation.getAllowTariffDetails();
            this.allowReducedPrice = apiTokenAndUrlInformation.getAllowReducedPrice();
            this.allowIntermediateStops = apiTokenAndUrlInformation.getAllowIntermediateStops();
            this.hvvReturnContSearchData = apiTokenAndUrlInformation.getHvvReturnContSearchData();
            this.apiName = apiTokenAndUrlInformation.getApiName();
            this.mic = apiTokenAndUrlInformation.getMic();
            this.mac = apiTokenAndUrlInformation.getMac();
            this.checksum = apiTokenAndUrlInformation.getChecksum();
            this.hafasRtMode = apiTokenAndUrlInformation.getHafasRtMode();
            this.clientId = apiTokenAndUrlInformation.getClientId();
            this.clientSecret = apiTokenAndUrlInformation.getClientSecret();
            this.clientVersion = apiTokenAndUrlInformation.getClientVersion();
            this.clientName = apiTokenAndUrlInformation.getClientName();
            this.clientType = apiTokenAndUrlInformation.getClientType();
            this.transfers = apiTokenAndUrlInformation.getTransfers();
            this.minTransferTime = apiTokenAndUrlInformation.getMinTransferTime();
            this.hafasProductionValue = apiTokenAndUrlInformation.getHafasProductionValue();
            this.forDisabledPersons = apiTokenAndUrlInformation.getForDisabledPersons();
            this.walkingSpeed = apiTokenAndUrlInformation.getWalkingSpeed();
            this.allowCoordinates = apiTokenAndUrlInformation.getAllowCoordinates();
            this.departureCoordinates = apiTokenAndUrlInformation.getDepartureCoordinates();
            this.arrivalCoordinates = apiTokenAndUrlInformation.getArrivalCoordinates();
            this.outputFormat = apiTokenAndUrlInformation.getOutputFormat();
            this.radius = apiTokenAndUrlInformation.getRadius();
            this.numberOfPersons = apiTokenAndUrlInformation.getNumberOfPersons();
            this.currency = apiTokenAndUrlInformation.getCurrency();
            this.sortDirection = apiTokenAndUrlInformation.getSortDirection();
            this.locoApiFlightPath = apiTokenAndUrlInformation.getLocoApiFlightPath();
            this.locoApiLocaterPath = apiTokenAndUrlInformation.getLocoApiLocaterPath();
            this.locoApiNearestAirportsPath = apiTokenAndUrlInformation.getLocoApiNearestAirportsPath();
            this.locoApiNationalTrainPath = apiTokenAndUrlInformation.getLocoApiNationalTrainPath();
            this.locoApiRegionalTrainPath = apiTokenAndUrlInformation.getLocoApiRegionalTrainPath();
            this.locoApiRideSharesPath = apiTokenAndUrlInformation.getLocoApiRideSharesPath();
            this.locoApiRidesPath = apiTokenAndUrlInformation.getLocoApiRidesPath();
            this.locoApiFootPath = apiTokenAndUrlInformation.getLocoApiFootPath();
            this.locoApiDirectConnectionPath = apiTokenAndUrlInformation.getLocoApiDirectConnectionPath();
            this.ages = apiTokenAndUrlInformation.getAges();
        }

        public ApiTokenAndUrlInformationBuilder(ApiTokenAndUrlInformationDto apiTokenAndUrlInformationDto) {
            this.protocol = apiTokenAndUrlInformationDto.getProtocol();
            this.host = apiTokenAndUrlInformationDto.getHost();
            this.port = apiTokenAndUrlInformationDto.getPort();
            this.apiVersion = apiTokenAndUrlInformationDto.getApiVersion();
            this.pathVariable = apiTokenAndUrlInformationDto.getPathVariable();
            this.departure = apiTokenAndUrlInformationDto.getDeparture();
            this.arrival = apiTokenAndUrlInformationDto.getArrival();
            this.departureDate = apiTokenAndUrlInformationDto.getDepartureDate();
            this.arrivalDate = apiTokenAndUrlInformationDto.getArrivalDate();
            this.xOriginationIpKey = apiTokenAndUrlInformationDto.getXOriginationIpKey();
            this.xOriginationIp = apiTokenAndUrlInformationDto.getXOriginationIp();
            this.authorizationKey = apiTokenAndUrlInformationDto.getAuthorizationKey();
            this.authorization = apiTokenAndUrlInformationDto.getAuthorization();
            this.path = apiTokenAndUrlInformationDto.getPath();
            this.hazelcastPath = apiTokenAndUrlInformationDto.getHazelcastPath();
            this.hazelcastWritePath = apiTokenAndUrlInformationDto.getHazelcastWritePath();
            this.hazelcastReadAllPath = apiTokenAndUrlInformationDto.getHazelcastReadAllPath();
            this.hazelcastSearchPath = apiTokenAndUrlInformationDto.getHazelcastSearchPath();
            this.germanRailJourneyDeatilsPath = apiTokenAndUrlInformationDto.getGermanRailJourneyDeatilsPath();
            this.germanRailDepartureBoardPath = apiTokenAndUrlInformationDto.getGermanRailDepartureBoardPath();
            this.germanRailArrivalBoardPath = apiTokenAndUrlInformationDto.getGermanRailArrivalBoardPath();
            this.germanRailLocationPath = apiTokenAndUrlInformationDto.getGermanRailLocationPath();
            this.germanRailDatePathVariable = apiTokenAndUrlInformationDto.getGermanRailDatePathVariable();
            this.stationId = apiTokenAndUrlInformationDto.getStationId();
            this.journeyDetailsId = apiTokenAndUrlInformationDto.getJourneyDetailsId();
            this.datePathVariable = apiTokenAndUrlInformationDto.getDatePathVariable();
            this.searchChRoutePathVariable = apiTokenAndUrlInformationDto.getSearchChRoutePathVariable();
            this.searchChResults = apiTokenAndUrlInformationDto.getSearchChResults();
            this.searchChDelayParameter = apiTokenAndUrlInformationDto.getSearchChDelayParameter();
            this.timePathVariable = apiTokenAndUrlInformationDto.getTimePathVariable();
            this.startLocation = apiTokenAndUrlInformationDto.getStartLocation();
            this.destinationLocation = apiTokenAndUrlInformationDto.getDestinationLocation();
            this.locationPath = apiTokenAndUrlInformationDto.getLocationPath();
            this.coordinatesPath = apiTokenAndUrlInformationDto.getCoordinatesPath();
            this.searchChTermParameter = apiTokenAndUrlInformationDto.getSearchChTermParameter();
            this.searchChStationId = apiTokenAndUrlInformationDto.getSearchChStationId();
            this.searchChStationCoordinateParameter = apiTokenAndUrlInformationDto.getSearchChStationCoordinateParameter();
            this.locationSearchTerm = apiTokenAndUrlInformationDto.getLocationSearchTerm();
            this.language = apiTokenAndUrlInformationDto.getLanguage();
            this.authentificationUser = apiTokenAndUrlInformationDto.getAuthentificationUser();
            this.authentificationType = apiTokenAndUrlInformationDto.getAuthentificationType();
            this.authentificationPassword = apiTokenAndUrlInformationDto.getAuthentificationPassword();
            this.stationListPathVariable = apiTokenAndUrlInformationDto.getStationListPathVariable();
            this.journeyPathVariable = apiTokenAndUrlInformationDto.getJourneyPathVariable();
            this.travelPointPathVariable = apiTokenAndUrlInformationDto.getTravelPointPathVariable();
            this.resultLength = apiTokenAndUrlInformationDto.getResultLength();
            this.distanceFromTravelPoint = apiTokenAndUrlInformationDto.getDistanceFromTravelPoint();
            this.resultLengthBeforeDepartureTime = apiTokenAndUrlInformationDto.getResultLengthBeforeDepartureTime();
            this.resultLengthAfterDepartureTime = apiTokenAndUrlInformationDto.getResultLengthAfterDepartureTime();
            this.tariff = apiTokenAndUrlInformationDto.getTariff();
            this.timeIsDeparture = apiTokenAndUrlInformationDto.getTimeIsDeparture();
            this.hvvFilterEquivalent = apiTokenAndUrlInformationDto.getHvvFilterEquivalent();
            this.hvvAllowTypeSwitch = apiTokenAndUrlInformationDto.getHvvAllowTypeSwitch();
            this.allowTariffDetails = apiTokenAndUrlInformationDto.getAllowTariffDetails();
            this.allowReducedPrice = apiTokenAndUrlInformationDto.getAllowReducedPrice();
            this.allowIntermediateStops = apiTokenAndUrlInformationDto.getAllowIntermediateStops();
            this.hvvReturnContSearchData = apiTokenAndUrlInformationDto.getHvvReturnContSearchData();
            this.apiName = apiTokenAndUrlInformationDto.getApiName();
            this.mic = apiTokenAndUrlInformationDto.getMic();
            this.mac = apiTokenAndUrlInformationDto.getMac();
            this.checksum = apiTokenAndUrlInformationDto.getChecksum();
            this.hafasRtMode = apiTokenAndUrlInformationDto.getHafasRtMode();
            this.clientId = apiTokenAndUrlInformationDto.getClientId();
            this.clientSecret = apiTokenAndUrlInformationDto.getClientSecret();
            this.clientVersion = apiTokenAndUrlInformationDto.getClientVersion();
            this.clientName = apiTokenAndUrlInformationDto.getClientName();
            this.clientType = apiTokenAndUrlInformationDto.getClientType();
            this.transfers = apiTokenAndUrlInformationDto.getTransfers();
            this.minTransferTime = apiTokenAndUrlInformationDto.getMinTransferTime();
            this.hafasProductionValue = apiTokenAndUrlInformationDto.getHafasProductionValue();
            this.forDisabledPersons = apiTokenAndUrlInformationDto.getForDisabledPersons();
            this.walkingSpeed = apiTokenAndUrlInformationDto.getWalkingSpeed();
            this.allowCoordinates = apiTokenAndUrlInformationDto.getAllowCoordinates();
            this.departureCoordinates = apiTokenAndUrlInformationDto.getDepartureCoordinates();
            this.arrivalCoordinates = apiTokenAndUrlInformationDto.getArrivalCoordinates();
            this.outputFormat = apiTokenAndUrlInformationDto.getOutputFormat();
            this.radius = apiTokenAndUrlInformationDto.getRadius();
            this.numberOfPersons = apiTokenAndUrlInformationDto.getNumberOfPersons();
            this.currency = apiTokenAndUrlInformationDto.getCurrency();
            this.sortDirection = apiTokenAndUrlInformationDto.getSortDirection();
            this.locoApiFlightPath = apiTokenAndUrlInformationDto.getLocoApiFlightPath();
            this.locoApiLocaterPath = apiTokenAndUrlInformationDto.getLocoApiLocaterPath();
            this.locoApiNearestAirportsPath = apiTokenAndUrlInformationDto.getLocoApiNearestAirportsPath();
            this.locoApiNationalTrainPath = apiTokenAndUrlInformationDto.getLocoApiNationalTrainPath();
            this.locoApiRegionalTrainPath = apiTokenAndUrlInformationDto.getLocoApiRegionalTrainPath();
            this.locoApiRideSharesPath = apiTokenAndUrlInformationDto.getLocoApiRideSharesPath();
            this.locoApiRidesPath = apiTokenAndUrlInformationDto.getLocoApiRidesPath();
            this.locoApiFootPath = apiTokenAndUrlInformationDto.getLocoApiFootPath();
            this.locoApiDirectConnectionPath = apiTokenAndUrlInformationDto.getLocoApiDirectConnectionPath();
            this.ages = apiTokenAndUrlInformationDto.getAges();
        }

        public ApiTokenAndUrlInformation build() {
            return new ApiTokenAndUrlInformation(this);
        }
    }
}
